magento/magento-coding-standard

Magento/Sniffs/PHP/FinalImplementationSniff.php
Magento/Tests/PHP/FinalImplementationUnitTest.inc
Magento/Tests/PHP/FinalImplementationUnitTest.php
Magento/ruleset.xml

Sniff for the rule "The use of final keyword is prohibited"

---

.travis.yml
Magento/Sniffs/Annotation/ClassAnnotationStructureSniff.php
Magento/Sniffs/Annotation/MethodAnnotationStructureSniff.php
Magento/Sniffs/Annotation/MethodArgumentsSniff.php
Magento/Sniffs/Classes/ObjectInstantiationSniff.php
Magento/Sniffs/Classes/ObjectManagerSniff.php
Magento/Sniffs/PHP/DateTimeSniff.php
Magento/Sniffs/PHP/FinalImplementationSniff.php
Magento/Sniffs/PHP/LiteralNamespacesSniff.php
Magento/Sniffs/Performance/EmptyCheckSniff.php
Magento/Sniffs/Security/IncludeFileSniff.php
Magento/Sniffs/Security/LanguageConstructSniff.php
Magento/Sniffs/Security/XssTemplateSniff.php
Magento/Sniffs/Strings/ExecutableRegExSniff.php
Magento/ruleset.xml

- made Magento Coding Standard to follow Magento Coding Standard

MM-5069: [EQP][Sniffs Consolidation] Follow Magento coding standard

---

Magento/ruleset.xml

Added new rule: Squiz.Operators.ValidLogicalOperators.
Solution for magento/magento-coding-standard#23: [New Rule] The use of literal logical operators MUST be avoided

[New Rule] The use of literal logical operators MUST be avoided #23.

---

Magento/Sniffs/Functions/StaticFunctionSniff.php
Magento/Tests/Functions/StaticFunctionUnitTest.inc
Magento/Tests/Functions/StaticFunctionUnitTest.php
Magento/ruleset.xml

#24: [New Rule] Static methods SHOULD NOT be used

---

Magento/ruleset.xml

Changed the severity of ValidLogicalOperators (Ensures logical operators `and` and `or` are not used.) because it's about `General code issue.` not `Code style issue (PSR2).` Reference: [wiki](https://github.com/magento/magento-coding-standard/wiki/Magento-Marketplace-Extensions-Verification).

Changed the severity of ValidLogicalOperators rule

---

Magento/Sniffs/Files/LineLengthSniff.php
Magento/Tests/Files/LineLengthUnitTest.inc
Magento/Tests/Files/LineLengthUnitTest.php
Magento/ruleset.xml

As suggested in https://github.com/magento/magento-coding-standard/issues/36#issuecomment-467913612, I moved the property declaration from the ruleset to the sniff itself.
I added an unit test but #6 should stay open as not all scenarios are covered yet.

Move LineLength from ruleset to sniff (fixes #36)

---

Magento/Sniffs/Classes/AbstractApiSniff.php
Magento/Tests/Classes/AbstractApiUnitTest.inc
Magento/Tests/Classes/AbstractApiUnitTest.php
Magento/ruleset.xml

#22: Impl. Abstract classes MUST NOT be marked as public

---

Magento/Sniffs/SQL/RawQuerySniff.php
Magento/Tests/SQL/RawQueryUnitTest.inc
Magento/Tests/SQL/RawQueryUnitTest.php
Magento/ruleset.xml

#48: Move RawQuerySniff

---

.travis.yml
README.md
composer.json

Fixed #55 Removed manual bin director. Updated README.md path and set composer and travis hooks to use vendor/bin instead.

Change bin directory

---

Magento2/Sniffs/Security/XssTemplateSniff.php
Magento2/Tests/Security/XssTemplateUnitTest.inc
Magento2/ruleset.xml

- resolved magento/magento-coding-standard#65;
- added more exclude for `*/Test/*` folders.

XssTemplateSniff does not detect some use cases

---

Magento2/Sniffs/Security/InsecureFunctionSniff.php
Magento2/Tests/Security/InsecureFunctionUnitTest.inc
Magento2/Tests/Security/InsecureFunctionUnitTest.php

Added `srand` and `mt_srand` to `InsecureFunctionSniff` to cover [UnsecureFunctionsUsageTest cases](https://github.com/magento/magento2/blob/2.3-develop/dev/tests/static/testsuite/Magento/Test/Legacy/_files/security/unsecure_php_functions.php).

Made InsecureFunctionSniff in line with UnsecureFunctionsUsageTest

---

Magento2/Sniffs/Files/LineLengthSniff.php
Magento2/Tests/Files/LineLengthUnitTest.inc
Magento2/Tests/Files/LineLengthUnitTest.php

* See #6 for details
* See https://github.com/magento/magento-coding-standard/issues/6#issuecomment-469030027 for an edge case that should be fixed in a separate issue

#6: Fix line length sniff when using translations

---

Magento2/ruleset.xml
composer.json
composer.lock

- added exclude for `_files` and `*Test.php` files
- fixed magento/magento-coding-standard#80

Added exclude for test files

---

README.md

The readme tells devs working on the Magento Coding Standard to verify their work by running the unit tests.
In addition, Travis checks if the sniffs themselves follow the Coding Standard - so devs should do this too for a quicker feedback loop.

Add note to check sniffer code by coding standard

---

Magento2/Sniffs/Classes/AbstractApiSniff.php
Magento2/Tests/Classes/AbstractApiUnitTest.1.inc
Magento2/Tests/Classes/AbstractApiUnitTest.2.inc
Magento2/Tests/Classes/AbstractApiUnitTest.php

The sniff doesn't work correctly when there is no comment in the class to test. Therefore, `$commentStartPtr` is `false` and the array lookup fails.
Note: the sniff in its current form fails if there are multiple abstract classes defined in one file and one of the classes doesn't have a comment. That happens because we search for the previous comment open tag, regardless of if the tag belongs to the current class we are looking at or to a previous one.
To fix this would be out of scope for #86, though.

#86: Fix AbstractApiSniff for classes without comment

---

Magento2/Sniffs/PHP/LiteralNamespacesSniff.php
Magento2/ruleset.xml

As discussed on https://github.com/magento/magento-coding-standard/issues/9 removed ```class_exists``` and ```interface_exists``` on LiteralNamespacesSniff.
Added exclude patterns.

Removed class exists checks and added exclude patterns

---

Magento2/Sniffs/Security/InsecureFunctionSniff.php
Magento2/Tests/Security/InsecureFunctionUnitTest.php
Magento2/ruleset.xml

```php
public $forbiddenFunctions = [
'assert' => null,
'create_function' => null,
'exec' => null,
'md5' => 'improved hash functions (SHA-256, SHA-512 etc.)',
'passthru' => null,
'pcntl_exec' => null,
'popen' => null,
'proc_open' => null,
'serialize' => '\Magento\Framework\Serialize\SerializerInterface::serialize',
'shell_exec' => null,
'system' => null,
'unserialize' => '\Magento\Framework\Serialize\SerializerInterface::unserialize',
'srand' => null,
'mt_srand' => null,
'mt_rand' => 'random_int',
];
```
Those functions are forbidden in Magento and its use will cause extension rejection on Marketplace.

REPO-209: [EQP] Increase the severity level to 10 for insecure functions

---

Magento2/ruleset.xml

As per upcoming updates https://github.com/magento/devdocs/pull/4425 `Squiz.Commenting.ClassComment` does not cover Magento 2 requirements and produces false positive findings.
Related tasks:
- DocBlock for function and methods https://github.com/magento/magento-coding-standard/issues/54
- DocBlock for class properties https://github.com/magento/magento-coding-standard/issues/58
- DocBlock for classes and interfaces https://github.com/magento/magento-coding-standard/issues/105
- DocBlock for constants https://github.com/magento/magento-coding-standard/issues/107

Removed Squiz.Commenting.ClassComment since it does not cover all Magento cases

---

Magento2/ruleset.xml

Added excludes for `phtml` files to keep consistency with https://github.com/magento/magento2/commit/12de4c5a9baf2972e9dbba5a82fb04213aa45f60
Additional info: https://github.com/magento/architecture/pull/160
Excludes and [ruleset.xml](https://github.com/magento/magento2/blob/2.3-develop/dev/tests/static/framework/Magento/ruleset.xml) will be removed in the future.

Added excludes for phtml files

---

composer.json
composer.lock

As per architecture requirements and [new versioning policy](https://github.com/magento/magento-coding-standard/wiki/Magento-Coding-Standard-Versioning) v.3 release preparation.

Bump coding standard version

---

Magento2/Sniffs/Commenting/ConstantsPHPDocFormattingSniff.php
Magento2/Tests/Commenting/ConstantsPHPDocFormattingUnitTest.1.inc
Magento2/Tests/Commenting/ConstantsPHPDocFormattingUnitTest.2.inc
Magento2/Tests/Commenting/ConstantsPHPDocFormattingUnitTest.php
Magento2/ruleset.xml

In compliance with [devdocs](https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#constants), rule will check if all occurrences of `define()` and `const` have dock block in front of them.
As #107 suggest, it will emit _warning_ with severity _5_.

Implement rule from #107

---

Magento2/Sniffs/CodeAnalysis/EmptyBlockSniff.php
Magento2/Tests/CodeAnalysis/EmptyBlockUnitTest.inc

Skip the test if the function name has "around" word

#95 : Empty FUNCTION statement detected should be allowed for around plugins

---

README.md

When running `composer install --no-dev` the bash command `[ $COMPOSER_DEV_MODE -eq 1]` will cause an exit code of 1. Build environments such as bitbucket piplines will often halt the build when encountering a none zero exit code. To resolve this, we force the exit code to be 0 with some boolean logic.

Prevent none zero exit code

---

Magento2/Sniffs/Commenting/ClassAndInterfacePHPDocFormattingSniff.php
Magento2/Sniffs/Commenting/ConstantsPHPDocFormattingSniff.php
Magento2/Sniffs/Commenting/PHPDocFormattingValidator.php
Magento2/Tests/Commenting/ClassAndInterfacePHPDocFormattingUnitTest.1.inc
Magento2/Tests/Commenting/ClassAndInterfacePHPDocFormattingUnitTest.2.inc
Magento2/Tests/Commenting/ClassAndInterfacePHPDocFormattingUnitTest.php
Magento2/Tests/Commenting/ConstantsPHPDocFormattingUnitTest.1.inc
Magento2/Tests/Commenting/ConstantsPHPDocFormattingUnitTest.2.inc
Magento2/Tests/Commenting/ConstantsPHPDocFormattingUnitTest.php

Implementation of rule from #131

Implement rule from #131

---

Magento2/Helpers/Commenting/PHPDocFormattingValidator.php
Magento2/Sniffs/Commenting/ClassAndInterfacePHPDocFormattingSniff.php
Magento2/Sniffs/Commenting/ConstantsPHPDocFormattingSniff.php
composer.json

magento/magento-coding-standard#144: Using coding standard as s reference is causing error

Using coding standard as s reference is causing error

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md

Added CODE_OF_CONDUCT.md and CONTRIBUTING.md

---

README.md

Fixed typos, headers layout, markdown (code fences languages), license URL updated to https.

README fixes - typos, layout, markdown, urls

---

Magento2/Sniffs/Methods/DeprecatedModelMethodSniff.php
Magento2/Tests/Methods/DeprecatedModelMethodUnitTest.inc
Magento2/Tests/Methods/DeprecatedModelMethodUnitTest.php
Magento2/ruleset.xml

Added sniff for #187 to discourage the use of Resource class from Model class.
Trigger Methods: 
- getResource()->load($object)
- getResource()->save($object)
- getResource()->delete($object)
Message: `Possible use of the deprecated model method 'getResource()' to 'save' the data detected.`

Added sniff for deprecated model methods. #187

---

Magento2/Sniffs/Functions/DiscouragedFunctionSniff.md
Magento2/Sniffs/Functions/DiscouragedFunctionSniff.php

This PR adds` getimagesize()`  to discouraged functions as it does not work with remote storage implementations.
Task: https://jira.corp.magento.com/browse/MC-38508

Discourage local-FS-only methods

---

.github/workflows/php.yml

As Travis stopped to work for some reason - I suggest moving to Github Actions, similar to https://github.com/magento/magento-semver/pull/62.
These changes I tested on my own repo - everything works fine:
https://github.com/ihor-sviziev/magento-coding-standard/runs/3143801880?check_suite_focus=true

Run tests on Github Actions

---

Magento2/Sniffs/Security/XssTemplateSniff.php
Magento2/Tests/Security/XssTemplateUnitTest.inc

One of our developers introduced a Parse Error into a template file. When `phpcs --standard=Magento2` ran as part of our automated testing process, it began using 100% CPU and never exited (until it was terminated automatically for taking too long). Investigation shows that the XSS Template sniff from this repository is at fault. I've managed to narrow down the cause and produced a testcase to reproduce this scenario. The proposed fix checks the return code of `PHP_CodeSniffer\Files\File::findNext()`, rather than blindly assuming this is an integer. I've not searched for other uses of this function within this codebase.

Avoid infinite loop when Parse Error occurs

---

.github/workflows/php.yml

This PR changes running tests on all supported PHP versions (7.2, 7.3, 7.4, 8.0) on the highest and lowest dependency versions to make sure we don't have any issues with dependencies.
Notes:
- The phpcs is **not** compatible with PHPUnit 8 and PHPUnit 9, which is required for PHP 8.  But the only latest version works fine with _ignoring platform requirements_ in composer. For now, we're ignoring them for PHP 8.0.
- PHP 8 is supported by phpcs 3.6.0. In prev. versions there were, so I'm running PHP 8 with only the highest dependencies
- As PHP 8 builds is failing - I added continue on error only for this type of builds, so the entire CI isn't failing (https://github.com/magento/magento-coding-standard/actions/runs/1070813599)
- I tested this PR together with #205 - it fixes errors on PHP …

Test on lowest and highest dependencies

---

Magento2/Sniffs/Annotation/AnnotationFormatValidator.php
Magento2/Sniffs/Annotation/MethodAnnotationStructureSniff.php
Magento2/Sniffs/Annotation/MethodArgumentsSniff.php
Magento2/Sniffs/GraphQL/ValidArgumentNameSniff.php
Magento2/Sniffs/GraphQL/ValidEnumValueSniff.php
Magento2/Sniffs/Html/HtmlBindingSniff.php
Magento2/Sniffs/Html/HtmlDirectiveSniff.php
Magento2/Sniffs/Less/AvoidIdSniff.php
Magento2/Sniffs/Less/BracesFormattingSniff.php
Magento2/Sniffs/Less/ClassNamingSniff.php
Magento2/Sniffs/Less/ColonSpacingSniff.php
Magento2/Sniffs/Less/ColourDefinitionSniff.php
Magento2/Sniffs/Less/CombinatorIndentationSniff.php
Magento2/Sniffs/Less/CommentLevelsSniff.php
Magento2/Sniffs/Less/ImportantPropertySniff.php
Magento2/Sniffs/Less/IndentationSniff.php
Magento2/Sniffs/Less/PropertiesLineBreakSniff.php
Magento2/Sniffs/Less/PropertiesSortingSniff.php
Magento2/Sniffs/Less/QuotesSniff.php
Magento2/Sniffs/Less/SelectorDelimiterSniff.php
Magento2/Sniffs/Less/SemicolonSpacingSniff.php
Magento2/Sniffs/Less/TokenizerSymbolsInterface.php
Magento2/Sniffs/Less/TypeSelectorConcatenationSniff.php
Magento2/Sniffs/Less/TypeSelectorsSniff.php
Magento2/Sniffs/Less/VariablesSniff.php
Magento2/Sniffs/Less/ZeroUnitsSniff.php
Magento2/Tests/GraphQL/AbstractGraphQLSniffUnitTestCase.php
Magento2/ruleset.xml

https://jira.corp.magento.com/browse/AC-201 Move phpcs checks from magento2 to magento-coding-standard repo

Move phpcs checks from magento2 to magento-coding-standard repo

---

Magento2/Sniffs/Legacy/AbstractBlockSniff.php
Magento2/Tests/Legacy/AbstractBlockUnitTest.inc
Magento2/Tests/Legacy/AbstractBlockUnitTest.php
Magento2/ruleset.xml

[AC-601](https://jira.corp.magento.com/browse/AC-601): Create phpcs static check for AbstractBlockTest
This PR is to start moving the legacy static checks we have on Magento2 codebase. This is covering the **AbstractBlock** changes.

AC-601: Create phpcs static check for AbstractBlockTest

---

Magento2/Helpers/Tokenizer/AbstractTokenizer.php
Magento2/Helpers/Tokenizer/Parameter.php
Magento2/Helpers/Tokenizer/Variable.php
Magento2/Sniffs/Html/HtmlDirectiveSniff.php

Just copied the original classes from the framework to fix the problem.

Fix magento/magento-coding-standard#214 with class not found

---

Magento2/Sniffs/Html/HtmlBindingSniff.php
Magento2/Tests/Html/HtmlBindingSniffUnitTest.1.inc
Magento2/Tests/Html/HtmlBindingUnitTest.php

This is port of the following test:
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/dev/tests/static/framework/tests/unit/testsuite/Magento/Sniffs/Html/HtmlBindingSniffTest.php

Add test coverage for HtmlBindingSniff

---

.github/workflows/php.yml
Magento2/Tests/GraphQL/AbstractGraphQLSniffUnitTestCase.php
PHP_CodeSniffer/Tests/Standards/AbstractSniffUnitTest.php
composer.json
composer.lock

This pull request (PR) provides the update of the `phpunit/phpunit` composer dependency to the latest version 9.5.8.
In additional, this PR provides the latest version of the class `PHP_CodeSnifferTestsStandards\AbstractSniffUnitTest` that has not released yet.
1. Fixes magento/magento2#33622

The `phpunit/phpunit` composer dependency has been updated to 9.5.8

---

Magento2/Sniffs/Namespaces/ImportsFromTestNamespaceSniff.php
Magento2/Tests/Namespaces/ImportsFromTestNamespaceUnitTest.inc

If a grouped use statement has a trailing coma like this:
```
use Magento\Something{
Foo,
Bar,
};
```
`findNext` on line 59 was returning false and next call was starting to search again from line 1 (`$next + 1`) and this function was looping indefinitely through input tokens.

Fix ImportsFromTestNamespace from lock on group use with trailing comma

---

.gitignore

This file gets created when running `vendor/bin/phpunit` and should not be tracked in version control.

Ignore PHPUnit results cache file

---

Magento2/Sniffs/Annotation/MethodArgumentsSniff.php
Magento2/Tests/Annotation/MethodArgumentsUnitTest.inc
Magento2/Tests/Annotation/MethodArgumentsUnitTest.php

We're seeing the following error when running Magento coding standard version 8 on one of the website we inherited:
PHP Fatal error:  Uncaught TypeError: strpos(): Argument #2 ($needle) must be of type string, null given in /srv/www/vendor/magento/magento-coding-standard/Magento2/Sniffs/Annotation/MethodArgumentsSniff.php:629
Stack trace:
#0 /srv/www/vendor/magento/magento-coding-standard/Magento2/Sniffs/Annotation/MethodArgumentsSniff.php(629): strpos('\\VendorName\\Mod...', NULL)
#1 /srv/www/vendor/magento/magento-coding-standard/Magento2/Sniffs/Annotation/MethodArgumentsSniff.php(515): Magento2\Sniffs\Annotation\MethodArgumentsSniff->validateFormattingConsistency(Array, Array, Object(PHP_CodeSniffer\Files\LocalFile), Array)
#2 …

Fix PHP Fatal error when docblock is invalid

---

Magento2/Sniffs/Less/ColonSpacingSniff.php
Magento2/Tests/Less/ColonSpacingUnitTest.less
Magento2/Tests/Less/ColonSpacingUnitTest.php

Catch newlines in the middle of a style definition and throw an error if any.
Resolves https://github.com/magento/magento-coding-standard/issues/242

AC-1100 Catch badly put newlines in LESS files

---

Magento2/Sniffs/Legacy/WidgetXMLSniff.php
Magento2/Tests/Legacy/WidgetXMLUnitTest.1.xml
Magento2/Tests/Legacy/WidgetXMLUnitTest.2.xml
Magento2/Tests/Legacy/WidgetXMLUnitTest.3.xml
Magento2/Tests/Legacy/WidgetXMLUnitTest.php
Magento2/ruleset.xml

\Magento\Test\Legacy\Magento\Widget\XmlTest  test for backwards-incompatible change in widget.xml structure

AC-661: Create phpcs static check for XmlTest

---

Magento2/Sniffs/Commenting/ClassPropertyPHPDocFormattingSniff.php
Magento2/Tests/Commenting/ClassPropertyPHPDocFormattingUnitTest.inc

Avoid triggering the "Missing PHP DocBlock for class property." warning when using typed class properties.

AC-1339: Detect comment for typed class properties

---

Magento2/Sniffs/Legacy/ObsoleteAclSniff.php
Magento2/Tests/Legacy/ObsoleteAclUnitTest.php
Magento2/Tests/Legacy/ObsoleteAclUnitTest.xml
Magento2/ruleset.xml

https://jira.corp.magento.com/browse/AC-674 Create phpcs static check for ObsoleteAclTest

AC-674: Create phpcs static check for ObsoleteAclTest

---

.github/workflows/php.yml
README.md
jscs/.jscsrc
package-lock.json
package.json

https://jira.corp.magento.com/browse/AC-1355 Move JSCS into magento-coding-standards repo

AC-1355: Move JSCS into magento-coding-standards repo

---

Magento2Framework/Sniffs/Header/CopyrightGraphQLSniff.php
Magento2Framework/Sniffs/Header/LicenseSniff.php
Magento2Framework/Tests/Header/CopyrightGraphQLUnitTest.1.graphqls
Magento2Framework/Tests/Header/CopyrightGraphQLUnitTest.2.graphqls
Magento2Framework/Tests/Header/CopyrightGraphQLUnitTest.3.graphqls
Magento2Framework/Tests/Header/CopyrightGraphQLUnitTest.4.graphqls
Magento2Framework/Tests/Header/CopyrightGraphQLUnitTest.php
Magento2Framework/ruleset.xml

Added copyright verification for graphqls files

Added copyright verification for graphqls files

---

Magento2/Sniffs/PHP/ArrayAutovivificationSniff.php
Magento2/Tests/PHP/ArrayAutovivificationUnitTest.inc
Magento2/Tests/PHP/ArrayAutovivificationUnitTest.php
Magento2/ruleset.xml

Added sniff for check autovivification on array.
Addresses backward incompatible change in PHP 8.1: https://wiki.php.net/rfc/autovivification_false
1. magento/magento2#34509

Add Sniff for check autovivification on array

---

Magento2/ruleset.xml

Excluded JS files for PSR sniffs and the indents requirements might conflict with eslint static tests

Excluded JS files for PSR sniffs

---

README.md

Remove JSCS references from README file on magento-coding-standard
https://jira.corp.magento.com/browse/AC-1509

AC-1509: Remove outdated JSCS static tests from magento

---

Magento2/Sniffs/Annotation/MethodArgumentsSniff.php

There are a lot of different rules that are defined within `Magento2/Sniffs/Annotation/MethodArgumentsSniff.php`. These all were reported as the same generic `Magento2.Annotation.MethodArguments.MethodArguments`; now these have a descriptive rule name, such as `Magento2.Annotation.MethodArguments.ParamOrder` or `Magento2.Annotation.MethodArguments.ExtraParam`.

Update rule names for better messaging

---

Magento2/Sniffs/Classes/DiscouragedDependenciesSniff.php
Magento2/Sniffs/Html/HtmlDirectiveSniff.php
Magento2/Sniffs/Less/CommentLevelsSniff.php
Magento2/Sniffs/Less/TokenizerSymbolsInterface.php
Magento2/Sniffs/Less/ZeroUnitsSniff.php
Magento2/Sniffs/Methods/DeprecatedModelMethodSniff.php
Magento2/ruleset.xml

Added Constant visibility check in the ruleset
1. Fixes magento/magento-coding-standard#174

Added Constant visibility in the ruleset

---

Magento2/Sniffs/PHP/ArrayAutovivificationSniff.php
Magento2/Tests/PHP/ArrayAutovivificationUnitTest.inc

Fixed sniff for check autovivification on array.
Addresses backward incompatible change in PHP 8.1: https://wiki.php.net/rfc/autovivification_false

Fixed code array autovivification

---

Magento2/Sniffs/Annotation/MethodArgumentsSniff.php
Magento2/Tests/Annotation/MethodArgumentsUnitTest.inc
Magento2/Tests/Annotation/MethodArgumentsUnitTest.php

The Warning 'Comment block is missing' is thrown when the attribute is present after the docblock.
example:
```
/**
* Check if given type is any type.
*
* @param string $type
* @return bool
*/
#[\ReturnTypeWillChange]
public function isTypeAny($type)
```
In such case our Sniff should ignore the attribute.

Fix Comment block is missing Failure when Attribute is present after the docblock

---

Magento2/ruleset.xml

There are a couple of sniffs duplicated between PHPCS and PHP Compatibility. I've picked the ones with better coverage after doing some tests.
| Excluded | Kept | Description |
| --- | --- | --- |
| Generic.PHP.DeprecatedFunctions | PHPCompatibility.FunctionUse.RemovedFunctions | Excluded one only catches deprecations and, due to it using `get_defined_functions()` to get deprecated methods, it doesn't include functions coming from extensions or deprecations from different PHP versions than the one which is running the sniff. |
| PHPCompatibility.Syntax.ForbiddenCallTimePassByReference | Generic.Functions.CallTimePassByReference | Both are equivalent, there is no special advantage of one over the other; in fact, call-time pass-by-reference is forbidden since PHP 5.4 so we can remove both …

AC-1895: Avoid having duplicated issues in magento-coding-standard

---

Magento2/ruleset.xml

| Excluded | Kept | Description |
| --------- | ----- | ----------- |
| PHPCompatibility.Keywords.ForbiddenNamesAsDeclared | Magento2.NamingConvention.ReservedWords | Both are equivalent. ReservedWords is customised for Magento2, so I think this is easier to extend it, if needed in the future |

AC-1895: Exclude sniff that is duplicated

---

Magento2/ruleset.xml

Preventing the error appearing on PHP 8.1:
```
------------------------------------------------------------------------------------------------------------------------------------------------------
1 | ERROR | An error occurred during processing; checking has been aborted. The error message was: trim(): Passing null to parameter #1 ($string) of
|       | type string is deprecated in
|       | /Users/sivashch/Projects/magento-coding-standard/vendor/phpcompatibility/php-compatibility/PHPCompatibility/Sniff.php on line 131
------------------------------------------------------------------------------------------------------------------------------------------------------
```
Test builds sensitivity improved in https://github.com/magento/magento-coding-standard/pull/367
Fixes …

PHP 8.1 Compatibility

---

Magento2/Sniffs/Templates/ThisInTemplateSniff.php
Magento2/Tests/Templates/ThisInTemplateUnitTest.inc.fixed
Magento2/Tests/Templates/ThisInTemplateUnitTest.php

Covered ThisInTemplateSniff with autofix. Autofix is replacing `$this` with `$block` in `.phtml` files
Autofixes are applied when executing `vendor/bin/phpcbf` instead of `vendor/bin/phpcs` (preserving most options/arguments).
Also, corrected helper call check: this test does not replace the original warning, but adds an additional one.
Resolves: https://jira.corp.magento.com/browse/AC-2221

Autofix for ThisInTemplate sniff

---

Magento2/Sniffs/Legacy/LayoutSniff.php
Magento2/Tests/Legacy/LayoutUnitTest.php

`Magento\Theme\Block\Html\Head\{Css,Link,Script}` classes are not present and are not used anymore.

Removed obsolete layout check

---

Magento2/Sniffs/PHPCompatibility/ForbiddenFinalPrivateMethodsSniff.php
Magento2/Tests/PHPCompatibility/ForbiddenFinalPrivateMethodsUnitTest.inc
Magento2/Tests/PHPCompatibility/ForbiddenFinalPrivateMethodsUnitTest.inc.fixed
Magento2/Tests/PHPCompatibility/ForbiddenFinalPrivateMethodsUnitTest.php

This code will autofix occurrences of `final private` methods which actually make no sense.
Note that original test code was customised for PHPCompatibility and didn't support autofix checking, so I had to adapt it to PHPCS unit tests-style. Also, warning was only issued if code had to be compatible with PHP 8.

AC-2222: [UCT Autofixing] PHPCompatibility.ForbiddenFinalPrivateMethods

---

Magento2/Sniffs/Functions/FunctionsDeprecatedWithoutArgumentSniff.php
Magento2/Tests/Functions/FunctionsDeprecatedWithoutArgumentUnitTest.inc
Magento2/Tests/Functions/FunctionsDeprecatedWithoutArgumentUnitTest.inc.fixed
Magento2/Tests/Functions/FunctionsDeprecatedWithoutArgumentUnitTest.php

https://jira.corp.magento.com/browse/AC-2219 Magento2.Functions.FunctionsDeprecatedWithoutArgument

AC-2219: Magento2.Functions.FunctionsDeprecatedWithoutArgument

---

composer.json
composer.lock
rector.php

This PR is to resolve this issue: [AC-2724](https://jira.corp.magento.com/browse/AC-2724). 
This is the PR in rector with all the explanation of why this rule was moved to other place:
https://github.com/rectorphp/rector-src/pull/1814/files

AC-2724: Update rector dependency to the latest version

---

Magento2/Tests/PHPCompatibility/BaseSniffTest.php
Magento2/Tests/PHPCompatibility/ForbiddenFinalPrivateMethodsUnitTest.php

While working on another change, I followed the [instructions in the README](https://github.com/magento/magento-coding-standard/blob/470f7a62b2433b0208eebaa6984af86c04736260/README.md#testing) which say to run `vendor/bin/phpunit && vendor/bin/phpcs --standard=Magento2 Magento2/ --extensions=php`. These reported errors which were unrelated to the changes I was making. This pull request solves those errors.
For reference, the output of the above commands used to be:
```sh
app@8a43352ec6d2:~/html$ vendor/bin/phpunit && vendor/bin/phpcs --standard=Magento2 Magento2/ --extensions=php
PHPUnit 9.5.20 #StandWithUkraine
...........................................W...................  63 / 204 ( 30%)
............................................................... 126 / 204 ( 61%) …
```

Fix warnings detected by phpcs & phpunit

---

Magento2/Helpers/Commenting/PHPDocFormattingValidator.php
Magento2/Tests/Commenting/ClassAndInterfacePHPDocFormattingUnitTest.php
Magento2/Tests/Commenting/ConstantsPHPDocFormattingUnitTest.1.inc
Magento2/Tests/Commenting/ConstantsPHPDocFormattingUnitTest.2.inc
Magento2/Tests/Commenting/ConstantsPHPDocFormattingUnitTest.php
composer.json
composer.lock

https://jira.corp.magento.com/browse/AC-3098 Fix function Helpers/Commenting/PHPDocFormattingValidator::hasDeprecatedWellFormatted
Updates:
- The @see tag must be present when there is a @deprecated tag.
- They both cannot be empty.
- If these conditions are not satisfied, a warning should be raised.

AC-3098: Update hasDeprecatedWellFormatted

---

Magento2/Sniffs/Annotation/MethodAnnotationStructureSniff.php
Magento2/Tests/Annotation/MethodAnnotationStructureUnitTest.inc
Magento2/Tests/Annotation/MethodAnnotationStructureUnitTest.php

https://jira.corp.magento.com/browse/AC-3099 Add a sniff for functions to display a warning when there is no @see tag
- There should be a sniff that checks that always that there is a @deprecated tag there exist a @see tag.
- Otherwise a warning should be displayed.
- There is a unit test that checks the behaviour stated above.

AC-3099: Add a sniff for functions to display a warning when there is no @see tag

---

Magento2/Sniffs/Commenting/ClassPropertyPHPDocFormattingSniff.php
Magento2/Tests/Commenting/ClassAndInterfacePHPDocFormattingUnitTest.php
Magento2/Tests/Commenting/ClassPropertyPHPDocFormattingUnitTest.inc
Magento2/Tests/Commenting/ClassPropertyPHPDocFormattingUnitTest.php

https://jira.corp.magento.com/browse/AC-3100 Add the @deprecated and @see tag check in Magento2/Sniffs/Commenting/ClassPropertyPHPDocFormattingSniff
- There Should be a sniff for properties that checks that always that there is a @deprecated tag there exist a @see tag.
- Otherwise a warning should be displayed.
- There is a unit test that checks the behaviour stated above.

AC-3100: Add the @deprecated and @see tag check to ClassPropertyPHPDocFormattingSniff

---

Magento2/Rector/Tests/AddArrayAccessInterfaceReturnTypes/config/configured_rule.php
Magento2/Rector/Tests/ReplaceMbStrposNullLimit/config/configured_rule.php
Magento2/Rector/Tests/ReplaceNewDateTimeNull/config/configured_rule.php
Magento2/Rector/Tests/ReplacePregSplitNullLimit/config/configured_rule.php

This PR fixes Rector tests by using RectorConfig instead of Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator

Fix Rector tests

---

Magento2/Helpers/Commenting/PHPDocFormattingValidator.php
Magento2/Tests/Annotation/MethodAnnotationStructureUnitTest.inc
Magento2/Tests/Commenting/ClassAndInterfacePHPDocFormattingUnitTest.1.inc
Magento2/Tests/Commenting/ClassAndInterfacePHPDocFormattingUnitTest.2.inc
Magento2/Tests/Commenting/ClassPropertyPHPDocFormattingUnitTest.inc
Magento2/Tests/Commenting/ConstantsPHPDocFormattingUnitTest.2.inc

For deprecated code with no replacement as that functionality is not provided anymore, use *This method will be removed in version 2.x.x without replacement* as keyword phrase in @deprecated description in addition to deprecation motif. That keyword phrase will help us identify @deprecated annotations that do not need @see.
https://github.com/magento-commerce/development-guild/issues/191
https://jira.corp.adobe.com/browse/LYNX-32

Allow to skip see tag in annotation with specific deprecated comment

---

Magento2/Sniffs/Commenting/ClassAndInterfacePHPDocFormattingSniff.php
Magento2/Tests/Commenting/ClassAndInterfacePHPDocFormattingUnitTest.1.inc
Magento2/Tests/Commenting/ClassAndInterfacePHPDocFormattingUnitTest.2.inc
Magento2/Tests/Commenting/ClassAndInterfacePHPDocFormattingUnitTest.php

Ref https://devdocs.magento.com/guides/v2.4/coding-standards/docblock-standard-general.html#documentation-space
Fixes #167

Add `@author` to forbidden tag list

---

Magento2/Sniffs/Security/XssTemplateSniff.php

This PR resolves the issue that in the `Magento2.Security.XssTemplate` sniff `FoundUnescaped` violations are sometimes incorrectly reported as `FoundNotAllowed`.
This currently happens from the moment the first `FoundNotAllowed` is reported, after that all violations are reported as `FoundNotAllowed`.
Consider the following code:
```phtml
<?= /* @disallowedAnnotation */ $foo ?>
<?= $bar ?>
```
The following is reported (the second warning has the wrong code):
```
FILE: /path/to/file.phtml
------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
------------------------------------------------------------------------------------------
1 | WARNING | Unescaped output detected.
|         | …
```

Resolve incorrect violation code in `Magento2.Security.XssTemplate` sniff

---

eslint/.eslintrc-magento

This is a small part of https://github.com/magento/magento-coding-standard/pull/347 as suggested in https://github.com/magento/magento-coding-standard/pull/347#issuecomment-999512251.
https://eslint.org/docs/rules/no-useless-call
https://eslint.org/docs/rules/no-useless-computed-key
https://eslint.org/docs/rules/no-useless-constructor
https://eslint.org/docs/rules/no-useless-escape
https://eslint.org/docs/rules/no-useless-rename
https://eslint.org/docs/rules/no-useless-return

[eslint] Disallow useless constructs

---

eslint/.eslintrc-magento

https://eslint.org/docs/rules/quotes
We shouldn't deter people from making code more readable.
1. [x] resolves magento/magento-coding-standard#403: Allow Use of Template Literals

Allow Use of Template Literals

---

Magento2/Sniffs/Security/XssTemplateSniff.php

This PR improves special annotation detection of the `Magento2.Security.XssTemplate` sniff by adding `T_SEMICOLON` as a statement separator. This resolves the issue that violations in a statement might be ignored by a special annotation in a previous/subsequent statement.
For example, consider the following file:
```phtml
<?php
/* @noEscape */ echo $foo;
echo $bar;
?>
<?=
$baz;
/* @noEscape */ echo $qux;
?>
```
This does not reported any violations of the `Magento2.Security.XssTemplate` sniff.
However, the statements involving `$bar` and `$baz` should report a `FoundUnescaped` violation.
This PR makes sure this is done, such that the following is reported:
```
FILE: /path/to/file.phtml
-----------------------------------------------------------------------------------------
FOUND 0 ERRORS …
```

Add semicolon as statement separator in the special annotation check of the `Magento2.Security.XssTemplate` sniff

---

eslint/.eslintrc-magento

This is a small part of https://github.com/magento/magento-coding-standard/pull/347 as suggested in https://github.com/magento/magento-coding-standard/pull/347#issuecomment-999512251.
https://eslint.org/docs/rules/keyword-spacing

[eslint] Enforce consistent spacing around keywords
