composer.json, composer.lock
=> REPO-66: [EQP][Sniffs Consolidation] Deliver Magento Coding Standard to magento2ce

Magento2/Sniffs/Performance/ForeachArrayMergeSniff.md, Magento2/ruleset.xml, composer.json, composer.lock
- added exclude for `*/Fixtures/*` files;
- added `ForeachArrayMergeSniff` documentation with `HowTo Fix` example;
- major version bump.
=> Pre 2.0.0 release improvements and fixes

Magento2/Tests/PHP/LiteralNamespacesUnitTest.inc, Magento2/Tests/PHP/LiteralNamespacesUnitTest.php
Resolved https://github.com/magento/magento-coding-standard/issues/7
=> Added unit test for LiteralNamespaces sniff

.travis.yml, composer.json, composer.lock
- version bump
- added PHP 7.3 to the `.travis.yml`
=> Version 4 Release

Magento2/ruleset.xml
This PR is regarding the test files which needs to ignored from magento coding standards
=> #136 : Add excludes for test files

Magento2/Sniffs/Functions/DiscouragedFunctionSniff.php
Fix according to actual method name in https://github.com/magento/magento2/blob/2.3/lib/internal/Magento/Framework/Filesystem/DriverInterface.php#L153
=> Fix typo in DiscouragedFunctionSniff

composer.json, composer.lock
=> V5 release

Magento2/Sniffs/Security/XssTemplateSniff.php
=> cleanup: doc url updated in comment

Magento2/Sniffs/Commenting/ClassAndInterfacePHPDocFormattingSniff.php
Fixed message according to https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html
=> Fixed confusing message for Class and Interface blocks

composer.json, composer.lock
Fixes magento/magento-coding-standard#191
- update PHP_CodeSniffer version
=> PHP 7.4 compatibility

Magento2/Sniffs/Functions/DiscouragedFunctionSniff.md, composer.json, composer.lock
=> Version 6 master update

.github/workflows/php.yml
Note: I ignored the Magento2/Tests folder, as it's not passing the validation
=> Run tests for all file types

Magento2/Sniffs/Annotation/AnnotationFormatValidator.php, Magento2/Sniffs/Annotation/MethodArgumentsSniff.php, Magento2/Tests/Annotation/MethodAnnotationStructureUnitTest.inc, Magento2/Tests/Annotation/MethodAnnotationStructureUnitTest.php, Magento2/Tests/Annotation/MethodArgumentsUnitTest.inc, Magento2/Tests/Annotation/MethodArgumentsUnitTest.php
[AC-958](https://jira.corp.magento.com/browse/AC-958)
=> AC-958: create unit test for Magento2\Annotation checks

composer.json
Moved abstract unit test to autoload-dev
Fixes https://github.com/magento/magento-coding-standard/issues/226
=> Moved abstract unit test to autoload-dev

Magento2/Tests/Less/TypeSelectorConcatenationUnitTest.less, Magento2/Tests/Less/TypeSelectorConcatenationUnitTest.php
https://jira.corp.magento.com/browse/AC-953 Create unit test for Magento2\Less\TypeSelectorConcatenationSniff check
=> AC-953: Create unit test for Magento2\Less\TypeSelectorConcatenationSniff check

Magento2/Tests/Less/VariablesUnitTest.less, Magento2/Tests/Less/VariablesUnitTest.php
https://jira.corp.magento.com/browse/AC-955
=> AC-955: Create unit test for Magento2\Less\VariablesSniff check

Magento2/ruleset.xml
Excluding xml files for php rules
=> AC-1307: PHP Syntax errors in xml files

composer.json, composer.lock
Increased Magento-coding-standard version to 11
=> Increased version to 11

Magento2/Tests/Eslint/AndSelfTest.js, Magento2/Tests/Eslint/BindUnbindTest.js, Magento2/Tests/Eslint/ClickEventShorthandTest.js, Magento2/Tests/Eslint/DelegateUndelegateTest.js, Magento2/Tests/Eslint/EventShorthandTest.js, Magento2/Tests/Eslint/SizeTest.js, Magento2/Tests/Eslint/TrimTest.js, Magento2/Tests/Legacy/CopyrightAnotherExtensionsFilesUnitTest.2.js, Magento2/Tests/Legacy/CopyrightAnotherExtensionsFilesUnitTest.4.js, eslint/rules/jquery-no-andSelf.js, eslint/rules/jquery-no-bind-unbind.js, eslint/rules/jquery-no-click-event-shorthand.js, eslint/rules/jquery-no-delegate-undelegate.js, eslint/rules/jquery-no-event-shorthand.js, eslint/rules/jquery-no-size.js, eslint/rules/jquery-no-trim.js, eslint/rules/utils.js
https://jira.corp.magento.com/browse/AC-1159 Move eslint tests to magento-coding-standard
=> AC-1159: Move eslint tests to magento-coding-standard

eslint/rules/utils.js
=> AC-1355: Move JSCS into magento-coding-standards repo

Magento2/Sniffs/Commenting/ClassPropertyPHPDocFormattingSniff.php, Magento2/Tests/Commenting/ClassPropertyPHPDocFormattingUnitTest.inc, phpunit.xml.dist
Fix https://github.com/magento/magento-coding-standard/issues/340
=> Fix Issue 340

eslint/.eslintrc-magento
This is a small part of https://github.com/magento/magento-coding-standard/pull/347 as suggested in https://github.com/magento/magento-coding-standard/pull/347#issuecomment-999512251.
https://eslint.org/docs/rules/yoda
=> Disallow Yoda Conditions in JavaScript files

Magento2/ruleset.xml
PR for https://github.com/magento/magento-coding-standard/issues/371
=> Improve: Exclude minified JS files.

package-lock.json, package.json
https://jira.corp.magento.com/browse/AC-2394 Update eslint npm dependency
Update eslint to version 8.8.0
=> AC-2394 Update eslint npm dependency

composer.json, composer.lock
=> Release v26

eslint/.eslintrc-magento, eslint/rules/utils.js
This is a small part of https://github.com/magento/magento-coding-standard/pull/347 as suggested in https://github.com/magento/magento-coding-standard/pull/347#issuecomment-999512251.
https://eslint.org/docs/rules/indent
=> [eslint] Enforce consistent indentation
